calculo para lograr reunir fondos 


In [13]:
price = [2,1,10]   #precio de venta 
type (price)



list

In [14]:
quantity_sold = [17,40,1]          #cantidad de venta 
type(quantity_sold)

list

In [15]:
price*quantity_sold

TypeError: ignored

In [16]:
import numpy as np
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [17]:
price_array*quantity_sold_array #Elementwice(elemto a elemto)
                                 

array([34, 40, 10])

In [18]:
cost_array = np.array([0.25,0.50,5.00]) #Costo de produccion

In [19]:
profit_array = price_array-cost_array #ganancia en cada producto
type(profit_array)
print(profit_array)

[1.75 0.5  5.  ]


In [20]:
profit_array > 2 #booleano para identificar en que producto obtuvimos mas de 2 de ganancia 

array([False, False,  True])

In [21]:
price_array = price_array +[7]
print(price_array)

[ 9  8 17]


In [22]:
price_array = price_array - [7] #reparando el error ateriror 
price_array = np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [23]:
price_array = np.append(price_array ,[4.50,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [24]:
print(price_array.dtype)


float64


In [25]:
price_array = np.delete(price_array,-1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [26]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Ejercicio Numpy de panaderia(core)

In [27]:
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])    #2 tartas,3bandejas ,16masgalenas ,5 panes                        
quantity_sold_array[1] = 39 #se rompio una galleta 
print(quantity_sold_array)                                                  

[17 39  1  2  3 16  5]


***Determinar la cantidad de dinero recaudado de la venta de cada elemto en la venta de la panaderia ***

In [28]:

sold_array = price_array*quantity_sold_array
print(sold_array)

[34.  39.  12.  14.  13.5 48.  20. ]


elemetos restantes al final de la venta 

In [29]:
quantity_leftover = [0,0,2,1,6,0,2]
quantity_leftover_array = np.array(quantity_leftover)
print(quantity_leftover)

[0, 0, 2, 1, 6, 0, 2]


In [31]:
sold_leftover_array = quantity_leftover_array *price_array/2 #sold es la venta 
print(sold_leftover_array)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


In [36]:
total_sold_array = sold_array + sold_leftover_array
print(total_sold_array)

[34.  39.  24.  17.5 27.  48.  24. ]


In [37]:
suma_total = np.sum(total_sold_array)
print(suma_total)

213.5
