calculo para lograr reunir fondos 


In [40]:
price = [2,1,10]   #precio de venta 
type (price)



list

In [41]:
quantity_sold = [17,40,1]          #cantidad de venta 
type(quantity_sold)

list

In [5]:
price*quantity_sold

TypeError: ignored

In [42]:
import numpy as np
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [43]:
price_array*quantity_sold_array #Elementwice(elemto a elemto)
                                 

array([34, 40, 10])

In [44]:
cost_array = np.array([0.25,0.50,5.00]) #Costo de produccion

In [45]:
profit_array = price_array-cost_array #ganancia en cada producto
type(profit_array)
print(profit_array)

[1.75 0.5  5.  ]


In [46]:
profit_array > 2 #booleano para identificar en que producto obtuvimos mas de 2 de ganancia 

array([False, False,  True])

In [47]:
price_array = price_array +[7]
print(price_array)

[ 9  8 17]


In [48]:
price_array = price_array - [7] #reparando el error ateriror 
price_array = np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


In [49]:
price_array = np.append(price_array ,[4.50,3,4,9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [39]:
print(price_array.dtype)


float64


In [50]:
price_array = np.delete(price_array,-1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [51]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


Ejercicio Numpy de panaderia(core)

In [52]:
quantity_sold_array = np.append(quantity_sold_array, [2,3,16,5])    #2 tartas,3bandejas ,16masgalenas ,5 panes                        
quantity_sold_array[1] = 39 #se rompio una galleta 
print(quantity_sold_array)                                                  

[17 39  1  2  3 16  5]


***Determinar la cantidad de dinero recaudado de la venta de cada elemto en la venta de la panaderia ***

In [55]:

price_array*quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

elemetos restantes al final de la venta 

In [72]:
quantity_leftover = [0,0,2,1,6,0,2]
quantity_leftover_array = np.array(quantity_leftover)
print(quantity_leftover)

[0, 0, 2, 1, 6, 0, 2]


In [73]:
price_leftover = [0,0,6,3.5,2.25,0,2]
price_leftover_array = np.array(price_leftover)
print(price_leftover_array)


[0.   0.   6.   3.5  2.25 0.   2.  ]


In [74]:
price_leftover_array*quantity_leftover_array


array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [ ]:
(price_leftover_array*)